
bluecloak:
  datasource:
    primary:
      jdbc-url: jdbc:h2:~/primary
      username: sa
      password:
      driver-class-name: org.h2.Driver
      connection-test-query: SELECT 1
      maximum-pool-size: 20
    secondary:
      jdbc-url: jdbc:h2:~/secondary
      username: sa
      password:
      driver-class-name: org.h2.Driver
      connection-test-query: SELECT 1
      maximum-pool-size: 20

